version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  hello-publisher:
    image: eclipse-mosquitto:2
    depends_on:
      - mosquitto
    entrypoint: >
      sh -c "
      sleep 2 &&
      mosquitto_pub -h mosquitto -p 1883 -t tests/alive -m 'Subscription received successfully' -r
      "

